export type Interest = { id: string; name: string; cat: string };

export const INTERESTS_SEED: Interest[] = [
  // Desporto
  { id:'futebol', name:'Futebol', cat:'Desporto' },
  { id:'basquetebol', name:'Basquetebol', cat:'Desporto' },
  { id:'tenis', name:'Ténis', cat:'Desporto' },
  { id:'padel', name:'Pádel', cat:'Desporto' },
  { id:'corrida', name:'Corrida', cat:'Desporto' },
  { id:'ciclismo', name:'Ciclismo', cat:'Desporto' },
  { id:'natacao', name:'Natação', cat:'Desporto' },
  { id:'ginasio', name:'Ginásio/Fitness', cat:'Desporto' },
  { id:'yoga', name:'Yoga', cat:'Desporto' },
  { id:'pilates', name:'Pilates', cat:'Desporto' },
  { id:'surf', name:'Surf', cat:'Desporto' },
  { id:'skate', name:'Skate', cat:'Desporto' },
  { id:'f1', name:'Fórmula 1', cat:'Desporto' },
  { id:'motogp', name:'MotoGP', cat:'Desporto' },
  { id:'esports', name:'eSports', cat:'Desporto' },

  // Entretenimento
  { id:'netflix', name:'Séries Netflix', cat:'Entretenimento' },
  { id:'hbo', name:'Séries HBO', cat:'Entretenimento' },
  { id:'disney', name:'Disney+', cat:'Entretenimento' },
  { id:'primevideo', name:'Prime Video', cat:'Entretenimento' },
  { id:'anime', name:'Anime', cat:'Entretenimento' },
  { id:'manga', name:'Mangá', cat:'Entretenimento' },
  { id:'cinema', name:'Cinema', cat:'Entretenimento' },
  { id:'terror', name:'Filmes de Terror', cat:'Entretenimento' },
  { id:'scifi', name:'Sci-Fi', cat:'Entretenimento' },
  { id:'comedia', name:'Comédia', cat:'Entretenimento' },
  { id:'truecrime', name:'True Crime', cat:'Entretenimento' },

  // Gaming
  { id:'gaming', name:'Gaming', cat:'Gaming' },
  { id:'fifa', name:'EA FC / FIFA', cat:'Gaming' },
  { id:'valorant', name:'Valorant', cat:'Gaming' },
  { id:'cs2', name:'CS2', cat:'Gaming' },
  { id:'lol', name:'League of Legends', cat:'Gaming' },
  { id:'fortnite', name:'Fortnite', cat:'Gaming' },
  { id:'minecraft', name:'Minecraft', cat:'Gaming' },
  { id:'gta', name:'GTA', cat:'Gaming' },
  { id:'switch', name:'Nintendo Switch', cat:'Gaming' },
  { id:'soulslike', name:'Soulslike', cat:'Gaming' },

  // Música
  { id:'musica', name:'Música', cat:'Música' },
  { id:'rock', name:'Rock', cat:'Música' },
  { id:'pop', name:'Pop', cat:'Música' },
  { id:'hiphop', name:'Hip-hop', cat:'Música' },
  { id:'eletronica', name:'Eletrónica', cat:'Música' },
  { id:'jazz', name:'Jazz', cat:'Música' },
  { id:'classica', name:'Clássica', cat:'Música' },
  { id:'kpop', name:'K-Pop', cat:'Música' },
  { id:'guitarra', name:'Tocar Guitarra', cat:'Música' },
  { id:'piano', name:'Tocar Piano', cat:'Música' },

  // Tecnologia
  { id:'programacao', name:'Programação', cat:'Tecnologia' },
  { id:'ai', name:'Inteligência Artificial', cat:'Tecnologia' },
  { id:'datascience', name:'Data Science', cat:'Tecnologia' },
  { id:'cyber', name:'Cibersegurança', cat:'Tecnologia' },
  { id:'robotica', name:'Robótica', cat:'Tecnologia' },
  { id:'web3', name:'Web3', cat:'Tecnologia' },
  { id:'hardware', name:'PC/Hardware', cat:'Tecnologia' },

  // Finanças/Negócios
  { id:'criptomoedas', name:'Criptomoedas', cat:'Finanças' },
  { id:'investing', name:'Investimentos', cat:'Finanças' },
  { id:'trading', name:'Trading', cat:'Finanças' },
  { id:'economia', name:'Economia', cat:'Finanças' },
  { id:'startups', name:'Startups', cat:'Negócios' },
  { id:'gestao', name:'Gestão', cat:'Negócios' },
  { id:'marketing', name:'Marketing Digital', cat:'Negócios' },

  // Estudo/Carreira
  { id:'engenharia', name:'Engenharia', cat:'Estudo' },
  { id:'biomedica', name:'Engenharia Biomédica', cat:'Estudo' },
  { id:'medicina', name:'Medicina', cat:'Estudo' },
  { id:'psicologia', name:'Psicologia', cat:'Estudo' },
  { id:'direito', name:'Direito', cat:'Estudo' },
  { id:'historia', name:'História', cat:'Estudo' },
  { id:'filosofia', name:'Filosofia', cat:'Estudo' },
  { id:'matematica', name:'Matemática', cat:'Estudo' },
  { id:'fisica', name:'Física', cat:'Estudo' },
  { id:'quimica', name:'Química', cat:'Estudo' },
  { id:'biologia', name:'Biologia', cat:'Estudo' },
  { id:'idiomas', name:'Aprender Idiomas', cat:'Estudo' },

  // Lifestyle
  { id:'viagens', name:'Viagens', cat:'Lifestyle' },
  { id:'mochilao', name:'Mochilão', cat:'Lifestyle' },
  { id:'roadtrip', name:'Road Trip', cat:'Lifestyle' },
  { id:'fotografia', name:'Fotografia', cat:'Lifestyle' },
  { id:'video', name:'Vídeo/YouTube', cat:'Lifestyle' },
  { id:'cozinha', name:'Cozinha', cat:'Lifestyle' },
  { id:'sushi', name:'Sushi', cat:'Lifestyle' },
  { id:'italiana', name:'Comida Italiana', cat:'Lifestyle' },
  { id:'bbq', name:'Churrasco/BBQ', cat:'Lifestyle' },
  { id:'vegan', name:'Vegan', cat:'Lifestyle' },
  { id:'cafes', name:'Café/Baristas', cat:'Lifestyle' },
  { id:'cha', name:'Chá', cat:'Lifestyle' },
  { id:'vinho', name:'Vinho', cat:'Lifestyle' },
  { id:'cerveja', name:'Cerveja Artesanal', cat:'Lifestyle' },
  { id:'campismo', name:'Campismo', cat:'Lifestyle' },
  { id:'trilhos', name:'Trilhos/Walking', cat:'Lifestyle' },
  { id:'jardim', name:'Jardinagem', cat:'Lifestyle' },
  { id:'diy', name:'DIY/Manualidades', cat:'Lifestyle' },
  { id:'moda', name:'Moda', cat:'Lifestyle' },
  { id:'design', name:'Design', cat:'Lifestyle' },
  { id:'arte', name:'Arte', cat:'Lifestyle' },
  { id:'meditacao', name:'Meditação', cat:'Lifestyle' },
  { id:'mindfulness', name:'Mindfulness', cat:'Lifestyle' },
  { id:'astrologia', name:'Astrologia', cat:'Lifestyle' },
  { id:'pets', name:'Animais de Estimação', cat:'Lifestyle' },
  { id:'caes', name:'Cães', cat:'Lifestyle' },
  { id:'gatos', name:'Gatos', cat:'Lifestyle' },

  // Board/Cartas
  { id:'xadrez', name:'Xadrez', cat:'Jogos de Mesa' },
  { id:'boardgames', name:'Board Games', cat:'Jogos de Mesa' },
  { id:'cartas', name:'Cartas/Poker', cat:'Jogos de Mesa' },

  // Leitura/Podcasts
  { id:'livros', name:'Leitura/Livros', cat:'Cultura' },
  { id:'fantasia', name:'Fantasia', cat:'Cultura' },
  { id:'scifibooks', name:'Sci-Fi (Livros)', cat:'Cultura' },
  { id:'podcasts', name:'Podcasts', cat:'Cultura' },

  // Extra para chegar perto de 100
  { id:'carros', name:'Carros', cat:'Hobbies' },
  { id:'motos', name:'Motas', cat:'Hobbies' },
  { id:'drones', name:'Drones', cat:'Hobbies' },
  { id:'smart_home', name:'Smart Home', cat:'Tecnologia' },
  { id:'saude', name:'Saúde & Bem-estar', cat:'Lifestyle' },
  { id:'voluntariado', name:'Voluntariado', cat:'Sociedade' },
  { id:'ambientalismo', name:'Ambientalismo', cat:'Sociedade' },
  { id:'minimalismo', name:'Minimalismo', cat:'Lifestyle' },
  { id:'economia_domestica', name:'Poupança & Gestão', cat:'Finanças' },
  { id:'bolsa', name:'Bolsa de Valores', cat:'Finanças' },
  { id:'imobiliario', name:'Imobiliário', cat:'Finanças' },
  { id:'colecionismo', name:'Colecionismo', cat:'Hobbies' }
];
